#!/bin/bash
rm -rf public/bowerjs
mkdir public/bowerjs
cp bower_components/jquery/jquery.min.js public/bowerjs
cp bower_components/jquery-ui/ui/minified/jquery-ui.min.js public/bowerjs
cp bower_components/bootstrap/dist/js/bootstrap.min.js public/bowerjs
cp bower_components/flexslider/jquery.flexslider-min.js public/bowerjs
cp bower_components/angular/angular.min.js public/bowerjs
cp bower_components/angular-route/angular-route.min.js public/bowerjs
cp bower_components/angular-flexslider/angular-flexslider.js public/bowerjs
cp bower_components/moment/min/moment-with-locales.min.js public/bowerjs
cp bower_components/angular-base64/angular-base64.min.js public/bowerjs
cp bower_components/angular-loading-bar/src/loading-bar.css public/bowercss
cp bower_components/angular-loading-bar/src/loading-bar.js public/bowerjs
cp bower_components/angular-ui-select/dist/select.min.css public/bowercss
cp bower_components/angular-ui-select/dist/select.min.js public/bowerjs
cp bower_components/angular-sanitize/angular-sanitize.min.js public/bowerjs
